# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build-release:
    name: Build artifacts
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build package
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/batonogov/pyinstaller-linux:v4.7.2
          options: |
            --platform linux/arm64
            --volume ${{ github.workspace }}/:/src
          run: |
            cd /src
            apt-get update && apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
            pip install -r requirements.txt
            pyinstaller app.spec

      - name: Bundle App
        run: |
          mkdir -p Artie/.artie && \
          cp -r ./dist/app ./assets ./config.json Artie/.artie/ && \
          cp ./mux_launch.sh ./mux_lang.ini Artie/ && \
          cp -r ./glyph Artie/ && \
          zip -r Artie.zip Artie && \
          mv Artie.zip Artie.muxapp

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: Artie.muxapp
